### ISSUE TITLE
UX - Don't need to confirm again after pressing Ctrl + S

### ISSUE THREAD

**Issue by ndaidong** [slap-editor/slap#321]
Hi there, 

In my view, when I press Ctrl + S that means I want to save immediately. Why I have to press an "Enter"? It seems not convenient with one more unnecessary step as such.

Do you share the same experience? How about your opinion?

Thanks,
Dong

**Comment by dbkaplun** [comment]
@ndaidong the reason that slap uses Ctrl+S for `saveAs` instead of `save` is <kbd>Ctrl+Shift+S</kbd> and the like are not supported by many terminal emulators, so <kbd>Ctrl+S</kbd> is mapped to `saveAs` and `save` is not currently mapped to any keybinding, to minimize confusion. Does that make sense?

You can change <kbd>Ctrl+S</kbd> to map to `save` instead of `saveAs`: #151

**Comment by ndaidong** [comment]
@dbkaplun That does make sense. Thank for your explaining. I will change the setting to get the expected behavior.
